---
name: Check docs quality
on:
  pull_request_target:
    branches:
      - main
      - master
    paths:
      - 'docs/**/*.md'

jobs:
  vale:
    name: Vale
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0
      - name: Run Vale cli
        uses: errata-ai/vale-action@reviewdog
        fail_on_error: true
        env:
          GITHUB_TOKEN: 
